sudo: false
language: ruby
rvm: 1.9.3
install:
  - pip install --user pycurl
  - pip install --user urlgrabber
  - git clone --depth 1 git://git.fedorahosted.org/git/pykickstart.git
  - (cd pykickstart && git checkout r2.20.1 && pip install --user .)
